# .github/workflows/release.yaml

on:
  release:
    types: [created]

env:
  AGENT_NAME: AmplifyTool
  DESCRIPTION: AmplifyTool

permissions:
    contents: write
    packages: write

jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: linux
        goarch: amd64
        ldflags: -X "github.com/Axway/agent-sdk/pkg/cmd.BuildVersion=${{ github.ref_name }}" -X "github.com/Axway/agent-sdk/pkg/cmd.SDKBuildVersion=v1.1.53" -X "github.com/Axway/agent-sdk/pkg/cmd.BuildAgentName=${{ env.AGENT_NAME }}" -X "github.com/Axway/agent-sdk/pkg/cmd.BuildAgentDescription=${{ env.DESCRIPTION }}"